import { useState, useEffect } from 'react';
import { BookOpen, Search, Plus, CheckCircle, Clock, Trash2, Download, LogOut, Sparkles, Target, TrendingUp } from 'lucide-react';

export default function LegalLensApp() {
    const [isLoggedIn, setIsLoggedIn] = useState(false);
    const [currentUser, setCurrentUser] = useState(null);
    const [loginForm, setLoginForm] = useState({ email: '', password: '' });
    const [loginError, setLoginError] = useState('');

    const [researchTasks, setResearchTasks] = useState([]);
    const [showAddTask, setShowAddTask] = useState(false);
    const [newTask, setNewTask] = useState({
        title: '',
        caseNumber: '',
        jurisdiction: 'Federal',
        practiceArea: 'General',
        priority: 'Medium',
        questions: ''
    });
    const [error, setError] = useState('');
    const [activeView, setActiveView] = useState('dashboard');

    useEffect(() => {
        if (isLoggedIn && currentUser) {
            loadTasks();
        }
    }, [isLoggedIn, currentUser]);

    const loadTasks = async () => {
        try {
            const result = await window.storage.get(`tasks:${currentUser.id}`);
            if (result && result.value) {
                setResearchTasks(JSON.parse(result.value));
            }
        } catch (err) {
            console.log('No existing tasks found, starting fresh');
        }
    };

    const saveTasks = async (tasks) => {
        try {
            await window.storage.set(`tasks:${currentUser.id}`, JSON.stringify(tasks));
        } catch (err) {
            setError('Failed to save tasks. Please try again.');
        }
    };

    const handleLogin = () => {
        setLoginError('');

        if (!loginForm.email || !loginForm.password) {
            setLoginError('Please enter both email and password');
            return;
        }

        const user = {
            id: 'user_' + loginForm.email.replace(/[^a-z0-9]/gi, '_'),
            name: loginForm.email.split('@')[0],
            email: loginForm.email,
            school: 'Law School Student'
        };

        setCurrentUser(user);
        setIsLoggedIn(true);
        setLoginForm({ email: '', password: '' });
    };

    const handleKeyPress = (e) => {
        if (e.key === 'Enter') {
            handleLogin();
        }
    };

    const handleLogout = () => {
        setIsLoggedIn(false);
        setCurrentUser(null);
        setResearchTasks([]);
        setActiveView('dashboard');
    };

    const addResearchTask = () => {
        setError('');

        if (!newTask.title.trim()) {
            setError('Task title is required');
            return;
        }

        const task = {
            id: Date.now(),
            ...newTask,
            status: 'pending',
            createdAt: new Date().toISOString(),
            completedAt: null,
            timeSpent: 0,
            findings: []
        };

        const updatedTasks = [...researchTasks, task];
        setResearchTasks(updatedTasks);
        saveTasks(updatedTasks);

        setNewTask({
            title: '',
            caseNumber: '',
            jurisdiction: 'Federal',
            practiceArea: 'General',
            priority: 'Medium',
            questions: ''
        });
        setShowAddTask(false);
    };

    const toggleTaskStatus = (taskId) => {
        const updatedTasks = researchTasks.map(task => {
            if (task.id === taskId) {
                const newStatus = task.status === 'completed' ? 'pending' : 'completed';
                return {
                    ...task,
                    status: newStatus,
                    completedAt: newStatus === 'completed' ? new Date().toISOString() : null
                };
            }
            return task;
        });
        setResearchTasks(updatedTasks);
        saveTasks(updatedTasks);
    };

    const deleteTask = (taskId) => {
        if (confirm('Are you sure you want to delete this research task?')) {
            const updatedTasks = researchTasks.filter(task => task.id !== taskId);
            setResearchTasks(updatedTasks);
            saveTasks(updatedTasks);
        }
    };

    const exportTask = (task) => {
        const report = `LEGAL RESEARCH REPORT
Generated by LegalLens AI

Case: ${task.caseNumber || 'N/A'}
Research Topic: ${task.title}
Jurisdiction: ${task.jurisdiction}
Practice Area: ${task.practiceArea}
Priority: ${task.priority}
Status: ${task.status}
Created: ${new Date(task.createdAt).toLocaleDateString()}
${task.completedAt ? 'Completed: ' + new Date(task.completedAt).toLocaleDateString() : ''}

RESEARCH QUESTIONS:
${task.questions || 'No specific questions provided'}

---
Note: This is an AI-assisted research tool for educational purposes.`;

        const blob = new Blob([report], { type: 'text/plain' });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `research_${task.id}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    const stats = {
        total: researchTasks.length,
        pending: researchTasks.filter(t => t.status === 'pending').length,
        completed: researchTasks.filter(t => t.status === 'completed').length,
        highPriority: researchTasks.filter(t => t.priority === 'High' && t.status === 'pending').length
    };

    if (!isLoggedIn) {
        return (
            <div className="min-h-screen bg-gradient-to-br from-purple-500 via-pink-500 to-orange-400 flex items-center justify-center p-4">
                <div className="bg-white rounded-3xl shadow-2xl p-10 w-full max-w-md">
                    <div className="text-center mb-8">
                        <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full mb-4">
                            <BookOpen className="text-white" size={40} />
                        </div>
                        <h1 className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent mb-2">
                            LegalLens AI
                        </h1>
                        <p className="text-gray-600 text-lg">
                            Your Legal Research Companion 📚
                        </p>
                    </div>

                    <div className="space-y-4">
                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-2">
                                Email Address
                            </label>
                            <input
                                type="email"
                                value={loginForm.email}
                                onChange={(e) => setLoginForm({ ...loginForm, email: e.target.value })}
                                onKeyPress={handleKeyPress}
                                placeholder="student@lawschool.edu"
                                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                            />
                        </div>

                        <div>
                            <label className="block text-sm font-semibold text-gray-700 mb-2">
                                Password
                            </label>
                            <input
                                type="password"
                                value={loginForm.password}
                                onChange={(e) => setLoginForm({ ...loginForm, password: e.target.value })}
                                onKeyPress={handleKeyPress}
                                placeholder="Enter password"
                                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                            />
                        </div>

                        {loginError && (
                            <div className="bg-red-50 border-2 border-red-200 text-red-700 px-4 py-3 rounded-xl text-sm">
                                {loginError}
                            </div>
                        )}

                        <button
                            onClick={handleLogin}
                            className="w-full bg-gradient-to-r from-purple-500 to-pink-500 text-white py-4 rounded-xl hover:from-purple-600 hover:to-pink-600 transition-all font-semibold text-lg shadow-lg"
                        >
                            Let's Go! 🚀
                        </button>
                    </div>

                    <div className="mt-6 p-4 bg-purple-50 rounded-2xl border-2 border-purple-100">
                        <p className="text-sm text-purple-800 text-center">
                            <strong>✨ Demo Mode:</strong> Enter any email and password to get started!
                        </p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-gradient-to-br from-purple-50 via-pink-50 to-orange-50">
            <header className="bg-white shadow-sm border-b-4 border-purple-300">
                <div className="max-w-7xl mx-auto px-6 py-5 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-pink-500 rounded-2xl flex items-center justify-center">
                            <BookOpen className="text-white" size={24} />
                        </div>
                        <div>
                            <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent">
                                LegalLens AI
                            </h1>
                            <p className="text-sm text-gray-600">{currentUser.school}</p>
                        </div>
                    </div>

                    <div className="flex items-center gap-4">
                        <div className="text-right hidden md:block">
                            <p className="text-sm font-semibold text-gray-800">👋 Hey, {currentUser.name}!</p>
                            <p className="text-xs text-gray-600">{currentUser.email}</p>
                        </div>
                        <button
                            onClick={handleLogout}
                            className="flex items-center gap-2 px-5 py-2 text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-xl transition-colors font-medium"
                        >
                            <LogOut size={18} />
                            Logout
                        </button>
                    </div>
                </div>
            </header>

            <nav className="bg-white border-b-2 border-purple-100">
                <div className="max-w-7xl mx-auto px-6">
                    <div className="flex gap-2">
                        <button
                            onClick={() => setActiveView('dashboard')}
                            className={`py-4 px-6 rounded-t-xl font-semibold transition-all ${activeView === 'dashboard'
                                    ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-lg'
                                    : 'text-gray-600 hover:bg-purple-50'
                                }`}
                        >
                            📊 Dashboard
                        </button>
                        <button
                            onClick={() => setActiveView('tasks')}
                            className={`py-4 px-6 rounded-t-xl font-semibold transition-all ${activeView === 'tasks'
                                    ? 'bg-gradient-to-r from-purple-500 to-pink-500 text-white shadow-lg'
                                    : 'text-gray-600 hover:bg-purple-50'
                                }`}
                        >
                            ✅ My Tasks
                        </button>
                    </div>
                </div>
            </nav>

            <main className="max-w-7xl mx-auto px-6 py-8">
                {error && (
                    <div className="mb-6 bg-red-50 border-2 border-red-200 text-red-700 px-5 py-4 rounded-2xl flex items-center justify-between shadow-sm">
                        <span className="font-medium">⚠️ {error}</span>
                        <button onClick={() => setError('')} className="text-red-700 hover:text-red-900 text-2xl">×</button>
                    </div>
                )}

                {activeView === 'dashboard' && (
                    <div>
                        <div className="mb-8">
                            <h2 className="text-3xl font-bold text-gray-800 mb-2">Your Progress 🎯</h2>
                            <p className="text-gray-600 text-lg">Keep track of all your legal research tasks in one place</p>
                        </div>

                        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
                            <div className="bg-white rounded-2xl shadow-lg p-6 border-2 border-purple-100 hover:shadow-xl transition-shadow">
                                <div className="flex items-center justify-between mb-3">
                                    <span className="text-gray-600 font-semibold">Total Tasks</span>
                                    <div className="w-12 h-12 bg-purple-100 rounded-xl flex items-center justify-center">
                                        <Target className="text-purple-600" size={24} />
                                    </div>
                                </div>
                                <p className="text-4xl font-bold text-gray-800">{stats.total}</p>
                                <p className="text-sm text-gray-500 mt-1">All time</p>
                            </div>

                            <div className="bg-white rounded-2xl shadow-lg p-6 border-2 border-orange-100 hover:shadow-xl transition-shadow">
                                <div className="flex items-center justify-between mb-3">
                                    <span className="text-gray-600 font-semibold">In Progress</span>
                                    <div className="w-12 h-12 bg-orange-100 rounded-xl flex items-center justify-center">
                                        <Clock className="text-orange-600" size={24} />
                                    </div>
                                </div>
                                <p className="text-4xl font-bold text-gray-800">{stats.pending}</p>
                                <p className="text-sm text-gray-500 mt-1">Keep going! 💪</p>
                            </div>

                            <div className="bg-white rounded-2xl shadow-lg p-6 border-2 border-green-100 hover:shadow-xl transition-shadow">
                                <div className="flex items-center justify-between mb-3">
                                    <span className="text-gray-600 font-semibold">Completed</span>
                                    <div className="w-12 h-12 bg-green-100 rounded-xl flex items-center justify-center">
                                        <CheckCircle className="text-green-600" size={24} />
                                    </div>
                                </div>
                                <p className="text-4xl font-bold text-gray-800">{stats.completed}</p>
                                <p className="text-sm text-gray-500 mt-1">Great job! 🎉</p>
                            </div>

                            <div className="bg-white rounded-2xl shadow-lg p-6 border-2 border-pink-100 hover:shadow-xl transition-shadow">
                                <div className="flex items-center justify-between mb-3">
                                    <span className="text-gray-600 font-semibold">High Priority</span>
                                    <div className="w-12 h-12 bg-pink-100 rounded-xl flex items-center justify-center">
                                        <Sparkles className="text-pink-600" size={24} />
                                    </div>
                                </div>
                                <p className="text-4xl font-bold text-gray-800">{stats.highPriority}</p>
                                <p className="text-sm text-gray-500 mt-1">Focus on these!</p>
                            </div>
                        </div>

                        <div className="bg-white rounded-2xl shadow-lg p-8 mb-8 border-2 border-purple-100">
                            <div className="flex items-center gap-3 mb-6">
                                <TrendingUp className="text-purple-600" size={28} />
                                <h3 className="text-2xl font-bold text-gray-800">Completion Progress</h3>
                            </div>
                            {stats.total > 0 ? (
                                <div>
                                    <div className="w-full bg-gray-200 rounded-full h-6 mb-4 overflow-hidden">
                                        <div
                                            className="bg-gradient-to-r from-purple-500 to-pink-500 h-6 rounded-full transition-all duration-500 flex items-center justify-end pr-3"
                                            style={{ width: `${(stats.completed / stats.total) * 100}%` }}
                                        >
                                            <span className="text-white text-sm font-bold">
                                                {Math.round((stats.completed / stats.total) * 100)}%
                                            </span>
                                        </div>
                                    </div>
                                    <p className="text-lg text-gray-700 font-medium">
                                        🎯 {stats.completed} out of {stats.total} tasks completed!
                                    </p>
                                </div>
                            ) : (
                                <div className="text-center py-8">
                                    <p className="text-gray-500 text-lg mb-4">No tasks yet - let's get started! 🚀</p>
                                    <p className="text-gray-400">Create your first research task to begin tracking progress</p>
                                </div>
                            )}
                        </div>

                        <div className="bg-gradient-to-br from-purple-500 to-pink-500 rounded-2xl shadow-xl p-8 text-white">
                            <h3 className="text-2xl font-bold mb-3">Ready to tackle some research? 📚</h3>
                            <p className="text-purple-100 mb-6 text-lg">
                                Create a new task and organize your legal research efficiently!
                            </p>
                            <button
                                onClick={() => {
                                    setActiveView('tasks');
                                    setShowAddTask(true);
                                }}
                                className="w-full bg-white text-purple-600 py-4 rounded-xl hover:bg-purple-50 transition-colors flex items-center justify-center gap-3 font-bold text-lg shadow-lg"
                            >
                                <Plus size={24} />
                                Create New Task
                            </button>
                        </div>
                    </div>
                )}

                {activeView === 'tasks' && (
                    <div>
                        <div className="flex items-center justify-between mb-8">
                            <div>
                                <h2 className="text-3xl font-bold text-gray-800 mb-2">My Research Tasks ✅</h2>
                                <p className="text-gray-600 text-lg">Organize and manage your legal research assignments</p>
                            </div>
                            <button
                                onClick={() => setShowAddTask(true)}
                                className="bg-gradient-to-r from-purple-500 to-pink-500 text-white px-6 py-3 rounded-xl hover:from-purple-600 hover:to-pink-600 transition-all flex items-center gap-2 font-semibold shadow-lg"
                            >
                                <Plus size={22} />
                                New Task
                            </button>
                        </div>

                        {showAddTask && (
                            <div className="bg-white rounded-2xl shadow-xl p-8 mb-8 border-4 border-purple-200">
                                <h3 className="text-2xl font-bold text-gray-800 mb-6 flex items-center gap-2">
                                    <Sparkles className="text-purple-600" size={28} />
                                    Create New Research Task
                                </h3>

                                <div className="space-y-5">
                                    <div>
                                        <label className="block text-sm font-bold text-gray-700 mb-2">
                                            📝 What are you researching? *
                                        </label>
                                        <input
                                            type="text"
                                            value={newTask.title}
                                            onChange={(e) => setNewTask({ ...newTask, title: e.target.value })}
                                            placeholder="e.g., Child custody standards in California"
                                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors text-lg"
                                        />
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                                        <div>
                                            <label className="block text-sm font-bold text-gray-700 mb-2">
                                                🔢 Case Number (Optional)
                                            </label>
                                            <input
                                                type="text"
                                                value={newTask.caseNumber}
                                                onChange={(e) => setNewTask({ ...newTask, caseNumber: e.target.value })}
                                                placeholder="e.g., 2024-CV-12345"
                                                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                                            />
                                        </div>

                                        <div>
                                            <label className="block text-sm font-bold text-gray-700 mb-2">
                                                📍 Jurisdiction
                                            </label>
                                            <select
                                                value={newTask.jurisdiction}
                                                onChange={(e) => setNewTask({ ...newTask, jurisdiction: e.target.value })}
                                                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                                            >
                                                <option>Federal</option>
                                                <option>California</option>
                                                <option>New York</option>
                                                <option>Texas</option>
                                                <option>Florida</option>
                                                <option>Other</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                                        <div>
                                            <label className="block text-sm font-bold text-gray-700 mb-2">
                                                ⚖️ Practice Area
                                            </label>
                                            <select
                                                value={newTask.practiceArea}
                                                onChange={(e) => setNewTask({ ...newTask, practiceArea: e.target.value })}
                                                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                                            >
                                                <option>General</option>
                                                <option>Family Law</option>
                                                <option>Personal Injury</option>
                                                <option>Criminal Defense</option>
                                                <option>Contract Law</option>
                                                <option>Employment Law</option>
                                                <option>Real Estate</option>
                                            </select>
                                        </div>

                                        <div>
                                            <label className="block text-sm font-bold text-gray-700 mb-2">
                                                ⭐ Priority Level
                                            </label>
                                            <select
                                                value={newTask.priority}
                                                onChange={(e) => setNewTask({ ...newTask, priority: e.target.value })}
                                                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                                            >
                                                <option>Low</option>
                                                <option>Medium</option>
                                                <option>High</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div>
                                        <label className="block text-sm font-bold text-gray-700 mb-2">
                                            💭 Research Questions / Notes
                                        </label>
                                        <textarea
                                            value={newTask.questions}
                                            onChange={(e) => setNewTask({ ...newTask, questions: e.target.value })}
                                            placeholder="What specific legal questions do you need to answer?"
                                            rows={4}
                                            className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-purple-500 transition-colors"
                                        />
                                    </div>

                                    <div className="flex gap-3 pt-2">
                                        <button
                                            onClick={addResearchTask}
                                            className="flex-1 bg-gradient-to-r from-purple-500 to-pink-500 text-white py-3 rounded-xl hover:from-purple-600 hover:to-pink-600 transition-all font-bold text-lg shadow-lg"
                                        >
                                            ✨ Create Task
                                        </button>
                                        <button
                                            onClick={() => setShowAddTask(false)}
                                            className="px-8 py-3 border-2 border-gray-300 text-gray-700 rounded-xl hover:bg-gray-50 transition-colors font-semibold"
                                        >
                                            Cancel
                                        </button>
                                    </div>
                                </div>
                            </div>
                        )}

                        <div className="space-y-5">
                            {researchTasks.length === 0 ? (
                                <div className="bg-white rounded-2xl shadow-lg p-16 text-center border-2 border-purple-100">
                                    <div className="w-24 h-24 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-6">
                                        <Search className="text-purple-600" size={48} />
                                    </div>
                                    <p className="text-gray-600 text-2xl font-bold mb-3">No research tasks yet! 📚</p>
                                    <p className="text-gray-500 text-lg mb-8">Start organizing your legal research by creating your first task</p>
                                    <button
                                        onClick={() => setShowAddTask(true)}
                                        className="bg-gradient-to-r from-purple-500 to-pink-500 text-white px-8 py-4 rounded-xl hover:from-purple-600 hover:to-pink-600 transition-all inline-flex items-center gap-3 font-bold text-lg shadow-lg"
                                    >
                                        <Plus size={24} />
                                        Create First Task
                                    </button>
                                </div>
                            ) : (
                                researchTasks.map(task => (
                                    <div
                                        key={task.id}
                                        className={`bg-white rounded-2xl shadow-lg p-6 border-l-8 hover:shadow-xl transition-all ${task.status === 'completed' ? 'border-green-500 bg-green-50' :
                                                task.priority === 'High' ? 'border-pink-500' :
                                                    task.priority === 'Medium' ? 'border-orange-500' : 'border-purple-500'
                                            }`}
                                    >
                                        <div className="flex items-start gap-4">
                                            <input
                                                type="checkbox"
                                                checked={task.status === 'completed'}
                                                onChange={() => toggleTaskStatus(task.id)}
                                                className="mt-2 w-6 h-6 text-purple-600 rounded-lg focus:ring-2 focus:ring-purple-500 cursor-pointer"
                                            />

                                            <div className="flex-1">
                                                <div className="flex items-start justify-between mb-3">
                                                    <div>
                                                        <h3 className={`text-xl font-bold mb-1 ${task.status === 'completed' ? 'text-gray-400 line-through' : 'text-gray-800'
                                                            }`}>
                                                            {task.title}
                                                        </h3>
                                                        {task.caseNumber && (
                                                            <p className="text-sm text-gray-600 font-medium">📋 Case: {task.caseNumber}</p>
                                                        )}
                                                    </div>

                                                    <div className="flex gap-2">
                                                        <button
                                                            onClick={() => exportTask(task)}
                                                            className="p-2 text-purple-600 bg-purple-100 hover:bg-purple-200 rounded-xl transition-colors"
                                                            title="Export Report"
                                                        >
                                                            <Download size={20} />
                                                        </button>
                                                        <button
                                                            onClick={() => deleteTask(task.id)}
                                                            className="p-2 text-pink-600 bg-pink-100 hover:bg-pink-200 rounded-xl transition-colors"
                                                            title="Delete Task"
                                                        >
                                                            <Trash2 size={20} />
                                                        </button>
                                                    </div>
                                                </div>

                                                <div className="flex flex-wrap gap-2 mb-4">
                                                    <span className="px-4 py-2 bg-purple-100 text-purple-800 text-sm rounded-full font-semibold">
                                                        📍 {task.jurisdiction}
                                                    </span>
                                                    <span className="px-4 py-2 bg-blue-100 text-blue-800 text-sm rounded-full font-semibold">
                                                        ⚖️ {task.practiceArea}
                                                    </span>
                                                    <span className={`px-4 py-2 text-sm rounded-full font-semibold ${task.priority === 'High' ? 'bg-pink-100 text-pink-800' :
                                                            task.priority === 'Medium' ? 'bg-orange-100 text-orange-800' :
                                                                'bg-gray-100 text-gray-800'
                                                        }`}>
                                                        ⭐ {task.priority} Priority
                                                    </span>
                                                    <span className={`px-4 py-2 text-sm rounded-full font-semibold ${task.status === 'completed' ? 'bg-green-100 text-green-800' : 'bg-yellow-100 text-yellow-800'
                                                        }`}>
                                                        {task.status === 'completed' ? '✅ Done!' : '⏳ Working on it'}
                                                    </span>
                                                </div>

                                                {task.questions && (
                                                    <div className="bg-purple-50 border-2 border-purple-100 rounded-xl p-4 mb-3">
                                                        <p className="text-sm text-gray-700 whitespace-pre-line font-medium">{task.questions}</p>
                                                    </div>
                                                )}

                                                <div className="flex items-center gap-4 text-sm text-gray-500">
                                                    <span>📅 Created: {new Date(task.createdAt).toLocaleDateString()}</span>
                                                    {task.completedAt && (
                                                        <span>✅ Completed: {new Date(task.completedAt).toLocaleDateString()}</span>
                                                    )}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    </div>
                )}
            </main>

            <footer className="bg-white border-t-2 border-purple-100 mt-12">
                <div className="max-w-7xl mx-auto px-6 py-6 text-center">
                    <p className="text-gray-600 font-medium mb-2">
                        <strong className="text-purple-600">LegalLens AI</strong> - Your Legal Research Companion
                    </p>
                    <p className="text-sm text-gray-500">
                        AI-assisted research tool for educational purposes. Not legal advice.
                    </p>
                </div>
            </footer>
        </div>
    );
}
